import "~/styles/globals.css";

import { type Metadata } from "next";

import { cn } from "~/lib/utils";
import { fontSans } from "~/lib/fonts";
import { ThemeProvider } from "~/components/theme-provider";
import { TailwindIndicator } from "~/components/tailwind-indicator";
import { Sider } from "~/components/sider";
import { RoochProviderWrapper } from "~/components/rooch-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "dark min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <RoochProviderWrapper>
            <div className="relative grid min-h-screen flex-1 md:grid-cols-[80px_minmax(0,1fr)]">
              <Sider />
              <div className="flex-1">{children}</div>
            </div>
            <TailwindIndicator />
          </RoochProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
